version: "3"
services:
  bdflask:
    image: snnn26/bdflask
    restart: always
    ports:
      - 5000:5000
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/usr/src/app
  mongo:
    image: mongo
    restart: always
  redis:
    image: redis
    restart: always
